### ISSUE TITLE
plugin not working after partial postback

### ISSUE THREAD

**Issue by Th3C0D3R** [wstoettinger/jquery.emojiarea.js#2]
Your plugin is not working anymore after partial postback like from updatepanle in asp.net
I need to call the plugin in Javascript without auto initialization.

is this somehow possible?

**Comment by wstoettinger** [comment]
this is how auto initialization is called:
```javascript
$('[data-emojiarea]').emojiarea();
```

knowing this, you could just omit the `data-emojiarea` attribute and call the function manually when needed:

```javascript
$('.your-jquery-selector').emojiarea();
```

I hope this helps!
